# Openshift File Integrity Operator
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "file-integrity-operator"
  namespace: "openshift-file-integrity"
spec:
  channel: "4.6"
  installPlanApproval: "Automatic"
  source: "redhat-operators"
  sourceNamespace: "openshift-marketplace"
  name: "file-integrity-operator"
